# Generated by Django 3.0.8 on 2022-08-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teamname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
