# Generated by Django 3.0.8 on 2022-08-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_project_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teamname',
            field=models.IntegerField(default=0),
        ),
    ]
